adding images and some info
GDGToulouse/site-devfest-toulouse-2018 pull request #1
Opened 2018-03-14 13:58 UTC by shprink

2018-03-15 04:49 UTC, davinkevin commented
Les fichiers Sketch et le PSD ne devraient ils pas être dans le Google Drive ? Ici ils allourdissent le repository git et ralentissent le déploiement.

2018-03-15 04:52 UTC, davinkevin requested changes
Les fichiers Sketch et le PSD ne devraient ils pas être dans le Google Drive ? Ici ils allourdissent le repository git et ralentissent le déploiement.

Sinon, OK pour le reste. Quand c'est bon pour toi, je ferai le rebase/edit commit/merge 😉

2018-03-18 13:29 UTC, shprink commented
Ok fait. Je suis pas en phase avec ne pas avoir les fichiers source dans le meme repo mais c'est fait.

2018-03-18 17:28 UTC, merged

2018-03-18 17:29 UTC, davinkevin commented
C'était une quesiton... 😞
Si tu penses que c'est mieux de les mettre ici, on les met 😊